[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "21S1YpfYcTucW4twabCsUpCkCMzi3qvDkF4mESBugnfW"
puppet-master = "5onw2hp6bWiKheSufVHiChyTohoiU9jRb1JZGc9e9iQz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
